<?php
/**
 * LaunchpadAuthorizationBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.88.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * LaunchpadAuthorizationBodyTest Class Doc Comment
 *
 * @category    Class
 * @description LaunchpadAuthorizationBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LaunchpadAuthorizationBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LaunchpadAuthorizationBody"
     */
    public function testLaunchpadAuthorizationBody()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "method_id"
     */
    public function testPropertyMethodId()
    {
    }

    /**
     * Test attribute "original_ip"
     */
    public function testPropertyOriginalIp()
    {
    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "sms_email"
     */
    public function testPropertySmsEmail()
    {
    }

    /**
     * Test attribute "template_id"
     */
    public function testPropertyTemplateId()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "email_name"
     */
    public function testPropertyEmailName()
    {
    }

    /**
     * Test attribute "sms_prefix"
     */
    public function testPropertySmsPrefix()
    {
    }

    /**
     * Test attribute "sms_number"
     */
    public function testPropertySmsNumber()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "expiry_hour"
     */
    public function testPropertyExpiryHour()
    {
    }

    /**
     * Test attribute "expiry_minute"
     */
    public function testPropertyExpiryMinute()
    {
    }

    /**
     * Test attribute "scoring"
     */
    public function testPropertyScoring()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }

    /**
     * Test attribute "trx_type"
     */
    public function testPropertyTrxType()
    {
    }

    /**
     * Test attribute "sca_exception"
     */
    public function testPropertyScaException()
    {
    }

    /**
     * Test attribute "merchant_data"
     */
    public function testPropertyMerchantData()
    {
    }
}
