<?php
/**
 * V1cardsSecureAuthenticationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.88.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * V1cardsSecureAuthenticationTest Class Doc Comment
 *
 * @category    Class
 * @description Node with user secure authentication details of a previous transaction to avoid future ACS.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1cardsSecureAuthenticationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1cardsSecureAuthentication"
     */
    public function testV1cardsSecureAuthentication()
    {
    }

    /**
     * Test attribute "cavv"
     */
    public function testPropertyCavv()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "eci"
     */
    public function testPropertyEci()
    {
    }

    /**
     * Test attribute "three_ds_server_trans_id"
     */
    public function testPropertyThreeDsServerTransId()
    {
    }

    /**
     * Test attribute "authenticacion_value"
     */
    public function testPropertyAuthenticacionValue()
    {
    }

    /**
     * Test attribute "ds_trans_id"
     */
    public function testPropertyDsTransId()
    {
    }

    /**
     * Test attribute "three_ds_version"
     */
    public function testPropertyThreeDsVersion()
    {
    }

    /**
     * Test attribute "authentication_flow"
     */
    public function testPropertyAuthenticationFlow()
    {
    }
}
