<?php
/**
 * V1formPaymentMerchantDataMerchantRiskIndicatorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.88.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * V1formPaymentMerchantDataMerchantRiskIndicatorTest Class Doc Comment
 *
 * @category    Class
 * @description Node with additional information of the business representing the evaluation of the level of risk of fraud for authentication. The delivery of this information is highly recommended
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1formPaymentMerchantDataMerchantRiskIndicatorTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1formPaymentMerchantDataMerchantRiskIndicator"
     */
    public function testV1formPaymentMerchantDataMerchantRiskIndicator()
    {
    }

    /**
     * Test attribute "delivery_email_address"
     */
    public function testPropertyDeliveryEmailAddress()
    {
    }

    /**
     * Test attribute "delivery_timeframe"
     */
    public function testPropertyDeliveryTimeframe()
    {
    }

    /**
     * Test attribute "gift_card_amount"
     */
    public function testPropertyGiftCardAmount()
    {
    }

    /**
     * Test attribute "gift_card_count"
     */
    public function testPropertyGiftCardCount()
    {
    }

    /**
     * Test attribute "gift_card_curr"
     */
    public function testPropertyGiftCardCurr()
    {
    }

    /**
     * Test attribute "pre_order_date"
     */
    public function testPropertyPreOrderDate()
    {
    }

    /**
     * Test attribute "pre_order_purchase_ind"
     */
    public function testPropertyPreOrderPurchaseInd()
    {
    }

    /**
     * Test attribute "reorder_items_ind"
     */
    public function testPropertyReorderItemsInd()
    {
    }

    /**
     * Test attribute "ship_indicator"
     */
    public function testPropertyShipIndicator()
    {
    }
}
