<?php
/**
 * V1formPaymentMerchantDataBillingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.88.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * V1formPaymentMerchantDataBillingTest Class Doc Comment
 *
 * @category    Class
 * @description V1formPaymentMerchantDataBilling
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1formPaymentMerchantDataBillingTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1formPaymentMerchantDataBilling"
     */
    public function testV1formPaymentMerchantDataBilling()
    {
    }

    /**
     * Test attribute "bill_addr_city"
     */
    public function testPropertyBillAddrCity()
    {
    }

    /**
     * Test attribute "bill_addr_country"
     */
    public function testPropertyBillAddrCountry()
    {
    }

    /**
     * Test attribute "bill_addr_line1"
     */
    public function testPropertyBillAddrLine1()
    {
    }

    /**
     * Test attribute "bill_addr_line2"
     */
    public function testPropertyBillAddrLine2()
    {
    }

    /**
     * Test attribute "bill_addr_line3"
     */
    public function testPropertyBillAddrLine3()
    {
    }

    /**
     * Test attribute "bill_addr_post_code"
     */
    public function testPropertyBillAddrPostCode()
    {
    }

    /**
     * Test attribute "bill_addr_state"
     */
    public function testPropertyBillAddrState()
    {
    }
}
