<?php
/**
 * V1sepaoperationsOperationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAYCOMET REST API
 *
 * PAYCOMET API REST for customers.
 *
 * OpenAPI spec version: 2.88.0
 * Contact: tecnico@paycomet.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * V1sepaoperationsOperationsTest Class Doc Comment
 *
 * @category    Class
 * @description Operations parameters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1sepaoperationsOperationsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1sepaoperationsOperations"
     */
    public function testV1sepaoperationsOperations()
    {
    }

    /**
     * Test attribute "operation_type"
     */
    public function testPropertyOperationType()
    {
    }

    /**
     * Test attribute "merchant_code"
     */
    public function testPropertyMerchantCode()
    {
    }

    /**
     * Test attribute "terminal_id_debtor"
     */
    public function testPropertyTerminalIdDebtor()
    {
    }

    /**
     * Test attribute "unique_id_creditor"
     */
    public function testPropertyUniqueIdCreditor()
    {
    }

    /**
     * Test attribute "company_name_creditor"
     */
    public function testPropertyCompanyNameCreditor()
    {
    }

    /**
     * Test attribute "iban_number_creditor"
     */
    public function testPropertyIbanNumberCreditor()
    {
    }

    /**
     * Test attribute "swift_code_creditor"
     */
    public function testPropertySwiftCodeCreditor()
    {
    }

    /**
     * Test attribute "company_type_creditor"
     */
    public function testPropertyCompanyTypeCreditor()
    {
    }

    /**
     * Test attribute "operation_order"
     */
    public function testPropertyOperationOrder()
    {
    }

    /**
     * Test attribute "operation_amount"
     */
    public function testPropertyOperationAmount()
    {
    }

    /**
     * Test attribute "operation_currency"
     */
    public function testPropertyOperationCurrency()
    {
    }

    /**
     * Test attribute "operation_datetime"
     */
    public function testPropertyOperationDatetime()
    {
    }

    /**
     * Test attribute "operation_concept"
     */
    public function testPropertyOperationConcept()
    {
    }
}
